#!/usr/bin/env python3
#coding = utf-8
while(1):
    name = input("Input characters you want to transform:")
    calc = 1
    i = 0
    for i in range(0,len(name)):
       calc = calc * ord(name[i])
print(hex(calc))
